FROM tensorflow/tensorflow:latest-gpu-jupyter
 
# add notebook folder to path
ENV PATH "$PATH:/tf/notebooks"

# set a password  setting token in config  password dsf2020
COPY jupyter_notebook_config.json /root/.jupyter/jupyter_notebook_config.json

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install --use-feature=2020-resolver -r requirements.txt
